extern crate proc_macro;

use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::token::Comma;
use syn::visit_mut::VisitMut;
use syn::{
    Attribute, DeriveInput, Error, FnArg, GenericArgument, GenericParam, Ident, ItemTrait, LitInt,
    PatIdent, Receiver, Token, TraitItem, TraitItemFn, Type, parse_macro_input, parse_quote,
};

fn has_option(attrs: &[Attribute], option_name: &str) -> bool {
    for attr in attrs
        .iter()
        .filter(|a| a.path().is_ident("canonical_structure"))
    {
        let mut found = false;

        // `parse_nested_meta` lets us walk through the arguments in #[canonical_structure(...)]
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident(option_name) {
                found = true;
            }
            // Continue parsing
            Ok(())
        });

        if found {
            return true;
        }
    }
    false
}

/// Generate a canonical structure type for a type `T` by decorating it with `#[derive(CanonicalStructure)]`.
/// Optional additional structure can be generated by adding `#[canonical_structure(eq, partial_ord, ord)]`.
/// The type must implement `Debug` and `Clone`. The optional additional structures may require `T` to implement further traits.
/// Requires `MetaType`, `Signature`, and `SetSignature` to be in scope. The optional additional structures may require further items to be in scope.
///
/// # Example
/// ```rust,ignore
/// #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, CanonicalStructure)]
/// #[canonical_structure(eq, partial_ord, ord)]
/// struct MyValue {
///     data: i64,
///     more_data: u32,
/// }
/// ```
/// `#[derive(CanonicalStructure)]` generates the following
/// ```rust,ignore
/// #[derive(Debug, Clone, PartialEq, Eq)]
/// struct MyValueCanonicalStructure {}
///
/// impl Signature for MyValueCanonicalStructure {}
///
/// impl MyValueCanonicalStructure {
///     fn new() -> Self {
///         Self {}
///     }
/// }
///
/// impl SetSignature for MyValueCanonicalStructure {
///     type Elem = MyValue;
///     fn validate_element(&self, _x: &Self::Elem) -> Result<(), String> {
///         Ok(())
///     }
/// }
///
/// impl MetaType for MyValue {
///     type Signature = MyValueCanonicalStructure;
///     fn structure() -> Self::Signature {
///         MyValueCanonicalStructure::new()
///     }
/// }
///
/// impl MyValue {
///     pub fn structure_ref() -> &'static MyValueCanonicalStructure {
///         static CELL: std::sync::OnceLock<MyValueCanonicalStructure> = std::sync::OnceLock::new();
///         CELL.get_or_init(|| MyValueCanonicalStructure::new())
///     }
/// }
/// ```
///
/// `#[canonical_structure(eq)]` requires `MyValue: Eq`, and `EqSignature` to be in scope. It generates the following
/// ```rust,ignore
/// impl EqSignature for MyValueCanonicalStructure
/// where
///     MyValue: Eq,
/// {
///     fn equal(&self, a: &Self::Elem, b: &Self::Elem) -> bool {
///         Eq::equal(a, b)
///     }
/// }
/// ```
///
/// `#[canonical_structure(partial_eq)]` requires `#[canonical_structure(eq)]`, `MyValue: PartialEq`, and `PartialEqSignature` to be in scope. It generates the following
/// ```rust,ignore
/// impl PartialOrdSignature for MyValueCanonicalStructure
/// where
///     MyValue: Ord,
/// {
///     fn partial_cmp(&self, a: &Self::Elem, b: &Self::Elem) -> Option<std::cmp::Ordering> {
///         Some(Ord::cmp(a, b))
///     }
/// }
/// ```
///
/// `#[canonical_structure(ord)]` requires `#[canonical_structure(partial_eq)]`, `MyValue: Ord`, and `OrdSignature` to be in scope. It generates the following
/// ```rust,ignore
/// impl OrdSignature for MyValueCanonicalStructure
/// where
///     MyValue: Ord,
/// {
///     fn cmp(&self, a: &Self::Elem, b: &Self::Elem) -> std::cmp::Ordering {
///         Ord::cmp(a, b)
///     }
///     fn sort<S: std::borrow::Borrow<Self::Elem>>(&self, mut a: Vec<S>) -> Vec<S> {
///         a.sort_unstable_by(|x, y| Ord::cmp(x.borrow(), y.borrow()));
///         a
///     }
/// }
/// ```
#[proc_macro_derive(CanonicalStructure, attributes(canonical_structure))]
pub fn derive_newtype(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    let name = input.ident;
    let vis = input.vis;
    let newtype_name = Ident::new(&format!("{name}CanonicalStructure"), name.span());

    let has_eq = has_option(&input.attrs, "eq");
    let has_partial_ord = has_option(&input.attrs, "partial_ord");
    let has_ord = has_option(&input.attrs, "ord");
    let has_finite = has_option(&input.attrs, "finite");
    let has_ord_finite = has_option(&input.attrs, "ord_finite");

    let impl_eq_signature = if has_eq {
        quote! {
            impl EqSignature for #newtype_name
                where #name: Eq
            {
                fn equal(self: &std::sync::Arc<Self>, a: &Self::Elem, b: &Self::Elem) -> bool {
                    a == b
                }
            }
        }
    } else {
        quote! {}
    };

    let impl_partial_ord_signature = if has_partial_ord {
        quote! {
            impl PartialOrdSignature for #newtype_name
                where #name: Ord
            {
                fn partial_cmp(self: &std::sync::Arc<Self>, a: &Self::Elem, b: &Self::Elem) -> Option<std::cmp::Ordering> {
                    Some(Ord::cmp(a, b))
                }
            }
        }
    } else {
        quote! {}
    };

    let impl_ord_signature = if has_ord {
        quote! {
            impl OrdSignature for #newtype_name
                where #name: Ord
            {
                fn cmp(self: &std::sync::Arc<Self>, a: &Self::Elem, b: &Self::Elem) -> std::cmp::Ordering {
                    Ord::cmp(a, b)
                }

                fn sort<S: std::borrow::Borrow<Self::Elem>>(self: &std::sync::Arc<Self>, mut a: Vec<S>) -> Vec<S> {
                    a.sort_unstable_by(|x, y| Ord::cmp(x.borrow(), y.borrow()));
                    a
                }
            }
        }
    } else {
        quote! {}
    };

    let impl_finite_signature = if has_finite {
        quote! {
            impl CountableSetSignature for #newtype_name {
                fn generate_all_elements(self: std::sync::Arc<Self>) -> impl Iterator<Item = Self::Elem> {
                    <#name as cantor::Finite>::iter()
                }
            }

            impl FiniteSetSignature for #newtype_name {
                fn list_all_elements(self: &std::sync::Arc<Self>) -> Vec<Self::Elem> {
                    self.list_all_elements_ordered()
                }

                fn size(self: &std::sync::Arc<Self>) -> Natural {
                    Natural::from(<#name as cantor::Finite>::COUNT)
                }
            }
        }
    } else {
        quote! {}
    };

    let impl_ord_finite_signature = if has_ord_finite {
        let test_enumeration_name = Ident::new(
            &format!("test_{name}CanonicalStructure_enumeration"),
            name.span(),
        );

        quote! {
            impl OrderedFiniteSetSignature for #newtype_name {
                fn list_all_elements_ordered(self: &std::sync::Arc<Self>) -> Vec<Self::Elem> {
                    <#name as cantor::Finite>::iter().collect()
                }

                fn element_to_enumeration(self: &std::sync::Arc<Self>, elem: &Self::Elem) -> Natural {
                    Natural::from(<#name as cantor::Finite>::index_of(elem.clone()))
                }

                fn enumeration_to_element(self: &std::sync::Arc<Self>, num: &Natural) -> Option<Self::Elem> {
                    if let Ok(num) = TryInto::<usize>::try_into(num) {
                        <#name as cantor::Finite>::nth(num)
                    } else {
                        None
                    }
                }
            }

            #[test]
            #[allow(non_snake_case)]
            fn #test_enumeration_name() {
                algebraeon_structures::assert_enumerated_ord_finite_set!(#name::structure(), <#name as cantor::Finite>::COUNT);
            }
        }
    } else {
        quote! {}
    };

    let expanded = quote! {
        #[derive(Debug, Clone, PartialEq, Eq)]
        #vis struct #newtype_name {}

        impl #newtype_name {
            fn new() -> Self {
                Self {}
            }
        }

        impl Signature for #newtype_name {}

        impl SetSignature for #newtype_name {
            type Elem = #name;

            fn validate_element(self: &std::sync::Arc<Self>, _x : &Self::Elem) -> Result<(), String> {
                Ok(())
            }
        }

        #impl_eq_signature
        #impl_partial_ord_signature
        #impl_ord_signature
        #impl_finite_signature
        #impl_ord_finite_signature

        impl MetaType for #name {
            type Signature = #newtype_name;

            fn structure() -> std::sync::Arc<Self::Signature> {
                std::sync::Arc::new(#newtype_name::new())
            }
        }
    };

    TokenStream::from(expanded)
}

/// In a structure trait decorated with `#[proc_macro_attribute]`, decorate a method with `#[skip_meta]` to exclude it from the auto-generated a meta structure trait.
///
/// # Example
/// The decorated structure trait
/// ```rust,ignore
/// #[signature_meta_trait]
/// pub trait MySignature: SetSignature {
///     fn special_element(&self) -> Self::Elem;
///     #[skip_meta]
///     fn binary_operation(&self, a: &Self::Elem, b: &Self::Elem) -> Self::Elem;
/// }
/// ```
/// produces the following meta structure trait.
/// ```rust,ignore
/// pub trait MetaMySignature: MetaType
/// where
///     Self::Signature: MySignature,
/// {
///     fn special_element() -> Self {
///         MySignature::special_element(Self::structure())
///     }
/// }
/// ```
#[proc_macro_attribute]
pub fn skip_meta(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Decorate a structure trait with this to auto-generate a meta structure trait.
///
/// # Receiver handling
/// How each method is forwarded depends on the type of its first argument:
/// * `self` or `&self` — the receiver is dropped and the body calls `Self::structure()`.
/// * `&mut self` — a compile error is emitted suggesting the method be excluded
///   with `#[skip_meta]`.
/// * any other first argument (or none) — the method is forwarded to the meta
///   type unchanged, with no special treatment of a receiver.
///
/// Methods whose return value borrows from `&self` (e.g. an iterator that holds a
/// `&'s self` reference) cannot be forwarded through the temporary returned by
/// `Self::structure()` and must be excluded with `#[skip_meta]`.
///
/// # Forwarding lifetimes
/// Generics (including lifetime parameters) on a trait method are preserved on
/// the generated meta method. When the first non-self argument is `&'a Self::Elem`
/// it is promoted to the meta method's receiver `&'a self`, forwarding the
/// lifetime so the return type may borrow from it. For example
/// `fn foo<'a>(&self, x: &'a Self::Elem, y: &'a Self::Elem) -> &'a Self::Elem`
/// becomes `fn foo<'a>(&'a self, y: &'a Self) -> &'a Self`.
///
/// # Example
/// The decorated structure trait
/// ```rust,ignore
/// #[signature_meta_trait]
/// pub trait MySignature: SetSignature {
///     fn special_element(&self) -> Self::Elem;
///     fn binary_operation(&self, a: &Self::Elem, b: &Self::Elem) -> Self::Elem;
/// }
/// ```
/// produces the following meta structure trait,
/// ```rust,ignore
/// pub trait MetaMySignature: MetaType
/// where
///     Self::Signature: MySignature,
/// {
///     fn special_element() -> Self {
///         Self::structure().special_element()
///     }
///     fn binary_operation(&self, b: &Self) -> Self {
///         Self::structure().binary_operation(self, b)
///     }
/// }
/// ```
/// and auto-implementation for meta structure types.
/// ```rust,ignore
/// impl<T> MetaMySignature for T
/// where
///     T: MetaType,
///     T::Signature: MySignature,
/// {
/// }
/// ```
#[proc_macro_attribute]
pub fn signature_meta_trait(_args: TokenStream, input: TokenStream) -> TokenStream {
    let trait_item = parse_macro_input!(input as ItemTrait);

    let expanded = expand_meta_trait(&trait_item);

    quote! {
        #trait_item
        #expanded
    }
    .into()
}

fn is_arc_self_type(ty: &Type) -> bool {
    let Type::Path(tp) = ty else {
        return false;
    };

    let Some(seg) = tp.path.segments.last() else {
        return false;
    };

    if seg.ident != "Arc" {
        return false;
    }

    let syn::PathArguments::AngleBracketed(args) = &seg.arguments else {
        return false;
    };

    matches!(
        args.args.first(),
        Some(syn::GenericArgument::Type(Type::Path(inner)))
            if inner.path.is_ident("Self")
    )
}

// check for `self: &Arc<Self>`
fn is_ref_arc_self(arg: &FnArg) -> bool {
    let FnArg::Receiver(receiver) = arg else {
        return false;
    };

    if receiver.colon_token.is_none() {
        return false;
    }

    let Type::Reference(r) = receiver.ty.as_ref() else {
        return false;
    };

    is_arc_self_type(r.elem.as_ref())
}

// check for `self: Arc<Self>`
fn is_arc_self(arg: &FnArg) -> bool {
    let FnArg::Receiver(receiver) = arg else {
        return false;
    };

    receiver.colon_token.is_some() && is_arc_self_type(receiver.ty.as_ref())
}

// check for `&self`
#[allow(unused)]
fn is_ref_self(arg: &FnArg) -> bool {
    match arg {
        FnArg::Receiver(receiver) => receiver.reference.is_some() && receiver.mutability.is_none(),
        FnArg::Typed(_) => false,
    }
}

/// Expand MetaTrait + impl
fn expand_meta_trait(trait_item: &ItemTrait) -> proc_macro2::TokenStream {
    let sig_trait_ident = &trait_item.ident;
    let meta_trait_ident = Ident::new(&format!("Meta{}", sig_trait_ident), Span::call_site());

    let generic_params = trait_item.generics.params.clone();

    let mut generic_arguments = Punctuated::<_, syn::token::Comma>::new();
    for param in generic_params.clone() {
        let arg = match param {
            GenericParam::Type(type_param) => {
                GenericArgument::Type(syn::Type::Path(syn::TypePath {
                    qself: None,
                    path: type_param.ident.into(),
                }))
            }
            GenericParam::Lifetime(lifetime_def) => {
                GenericArgument::Lifetime(lifetime_def.lifetime)
            }
            GenericParam::Const(const_param) => {
                GenericArgument::Const(syn::Expr::Path(syn::ExprPath {
                    attrs: Vec::new(),
                    qself: None,
                    path: const_param.ident.into(),
                }))
            }
        };
        generic_arguments.push(arg);
    }

    let mut meta_methods = Vec::new();
    let mut errors = Vec::new();
    for item in &trait_item.items {
        if let TraitItem::Fn(TraitItemFn { attrs, sig, .. }) = item {
            if attrs.iter().any(|attr| attr.path().is_ident("skip_meta")) {
                continue;
            }

            enum ReceiverType {
                RefArcSelf,
                ArcSelf,
            }

            let meta_sig = sig.clone();

            let receiver_type = if let Some(first_arg) = meta_sig.inputs.first() {
                if is_ref_arc_self(first_arg) {
                    Some(ReceiverType::RefArcSelf)
                } else if is_arc_self(first_arg) {
                    Some(ReceiverType::ArcSelf)
                } else {
                    None
                }
            } else {
                None
            };

            match receiver_type {
                None => {
                    errors.push(
                    Error::new_spanned(
                        meta_sig,
                        "signature_meta_trait method must start `&self`, `self: &Arc<Self>` or `self: Arc<Self>`",
                    )
                    .to_compile_error(),
                );
                }
                Some(receiver_type) => {
                    // Receiver is `self: Arc<Self>`
                    let mut meta_sig_without_self = meta_sig.clone();
                    meta_sig_without_self.inputs =
                        meta_sig_without_self.inputs.into_iter().skip(1).collect();
                    ReplaceSelfSetSignature {
                        sig_trait_ident: sig_trait_ident.clone(),
                        generic_arguments: generic_arguments.clone(),
                    }
                    .visit_signature_mut(&mut meta_sig_without_self);

                    let ident = meta_sig_without_self.ident.clone();

                    let mut meta_args = Vec::new();
                    #[allow(clippy::never_loop)]
                    for arg in &mut meta_sig_without_self.inputs {
                        match arg {
                            FnArg::Typed(pat_type) => match pat_type.pat.as_mut() {
                                syn::Pat::Ident(pat_ident) => {
                                    pat_ident.mutability = None;
                                    meta_args.push(pat_ident.clone());
                                }
                                _ => {
                                    return Error::new_spanned(
                                        trait_item,
                                        "Invalid pattern in argument list. Must be a plain Ident.",
                                    )
                                    .to_compile_error();
                                }
                            },
                            FnArg::Receiver(_) => {
                                panic!();
                            }
                        }
                    }

                    if let Some(first) = sig.inputs.iter().nth(1) {
                        match first {
                            FnArg::Receiver(_) => {}
                            FnArg::Typed(pat_type) => match pat_type.ty.as_ref() {
                            syn::Type::Reference(type_reference) => {
                                if let syn::Type::Path(type_path) =
                                    type_reference.elem.as_ref()
                                    && is_type_path_self_set(type_path)
                                {
                                    // if the first argument is `a: &'x Self::Elem` then replace it with `&'x self` in the meta type
                                    // if the first argument is `a: &mut Self::Elem` then replace it with `&mut self` in the meta type
                                    // The argument's lifetime is forwarded onto the receiver so the return type may borrow from it.
                                    let lifetime = type_reference.lifetime.clone();
                                    meta_args[0] = PatIdent {
                                        attrs: vec![],
                                        by_ref: None,
                                        mutability: None,
                                        ident: Ident::new("self", Span::call_site()),
                                        subpat: None,
                                    };
                                    meta_sig_without_self.inputs[0] = FnArg::Receiver(Receiver {
                                        attrs: vec![],
                                        reference: Some((
                                            syn::token::And {
                                                spans: [Span::call_site()],
                                            },
                                            lifetime.clone(),
                                        )),
                                        mutability: type_reference.mutability,
                                        self_token: syn::token::SelfValue {
                                            span: Span::call_site(),
                                        },
                                        colon_token: None,
                                        ty: Box::new(syn::Type::Reference(
                                            syn::TypeReference {
                                                and_token: syn::token::And {
                                                    spans: [Span::call_site()],
                                                },
                                                lifetime,
                                                mutability: type_reference.mutability,
                                                elem: Box::new(syn::Type::Path(
                                                    syn::TypePath {
                                                        qself: None,
                                                        path: syn::Path::from(Ident::new(
                                                            "Self",
                                                            Span::call_site(),
                                                        )),
                                                    },
                                                )),
                                            },
                                        )),
                                    });
                                }
                            }
                            syn::Type::Path(type_path)
                                // if the first argument is `a: Self::Elem` then replace it with `self` in the meta type (TODO)
                                if is_type_path_self_set(type_path) => {
                                    meta_args[0] = PatIdent {
                                        attrs: vec![],
                                        by_ref: None,
                                        mutability: None,
                                        ident: Ident::new("self", Span::call_site()),
                                        subpat: None,
                                    };
                                    meta_sig_without_self.inputs[0] = FnArg::Receiver(Receiver {
                                        attrs: vec![],
                                        reference: None,
                                        mutability: None,
                                        self_token: syn::token::SelfValue {
                                            span: Span::call_site(),
                                        },
                                        colon_token: None,
                                        ty: Box::new(syn::Type::Path(syn::TypePath {
                                            qself: None,
                                            path: syn::Path::from(Ident::new(
                                                "Self",
                                                Span::call_site(),
                                            )),
                                        })),
                                    });
                                }
                            _ => {}
                        },
                        }
                    }

                    let trait_ident = trait_item.ident.clone();

                    match receiver_type {
                        ReceiverType::RefArcSelf => {
                            meta_methods.push(quote! {
                                #(#attrs)*
                                #meta_sig_without_self {
                                    #trait_ident::#ident(&Self::structure(), #(#meta_args),*)
                                }
                            });
                        }
                        ReceiverType::ArcSelf => {
                            meta_methods.push(quote! {
                                #(#attrs)*
                                #meta_sig_without_self {
                                    #trait_ident::#ident(Self::structure(), #(#meta_args),*)
                                }
                            });
                        }
                    }
                }
            }
        }
    }

    let where_clauses = if let Some(where_clause) = &trait_item.generics.where_clause {
        let mut predicates = where_clause.predicates.clone();
        for predicate in &mut predicates {
            ReplaceSelfSetSignature {
                sig_trait_ident: sig_trait_ident.clone(),
                generic_arguments: generic_arguments.clone(),
            }
            .visit_where_predicate_mut(predicate);
        }
        quote!(#predicates)
    } else {
        quote!()
    };

    let q = quote! {
        pub trait #meta_trait_ident<#generic_params>: MetaType
        where
            Self::Signature: #sig_trait_ident<#generic_arguments>,
            #where_clauses
        {
            #(#meta_methods)*
        }

        impl<T : MetaType, #generic_params> #meta_trait_ident<#generic_arguments> for T
        where
            T::Signature: #sig_trait_ident<#generic_arguments>,
            #where_clauses
        {
        }

        #(#errors)*
    };

    // if trait_item.ident == "FunctionsDomainPermutationActionSignature" {
    //     eprintln!("{}", q);
    //     loop {}
    // }

    q
}

struct ReplaceSelfSetSignature {
    sig_trait_ident: Ident,
    generic_arguments: Punctuated<GenericArgument, Comma>,
}
impl VisitMut for ReplaceSelfSetSignature {
    fn visit_type_path_mut(&mut self, ty: &mut syn::TypePath) {
        syn::visit_mut::visit_type_path_mut(self, ty);
        if is_type_path_self_set(ty) {
            // Replace `Self::Elem` with `Self`
            *ty = syn::parse_quote!(Self);
        } else if ty.qself.is_none()
            && ty.path.segments.len() == 1
            && ty.path.segments[0].ident == "Self"
            && ty.path.segments[0].arguments.is_empty()
        {
            // Replace `Self` with `Self::Signature`
            *ty = syn::parse_quote!(Self::Signature);
        } else if ty.qself.is_none()
            && ty.path.segments.len() >= 2
            && ty.path.segments[0].ident == "Self"
            && ty.path.segments[0].arguments.is_empty()
        {
            // Replace `Self::Foo::Bar` with `<Self::Signature as #sig_trait_ident<Generics, ...>>::Foo::Bar`
            let sig_trait_ident = &self.sig_trait_ident;
            let generic_arguments = &self.generic_arguments;
            ty.path.segments[0] = syn::parse_quote!(#sig_trait_ident<#generic_arguments>);
            ty.qself = Some(syn::QSelf {
                lt_token: syn::token::Lt {
                    spans: [Span::call_site()],
                },
                ty: syn::parse_quote!(Self::Signature),
                position: 1,
                as_token: Some(syn::token::As {
                    span: Span::call_site(),
                }),
                gt_token: syn::token::Gt {
                    spans: [Span::call_site()],
                },
            });
        }
    }
}

fn is_type_path_self_set(ty: &syn::TypePath) -> bool {
    ty.qself.is_none()
        && ty.path.segments.len() == 2
        && ty.path.segments[0].ident == "Self"
        && ty.path.segments[1].ident == "Elem"
        && ty.path.segments[1].arguments.is_empty()
}

struct RepeatPrimesInput {
    n: LitInt,
    _comma: Token![,],
    placeholder: Ident,
    _arrow: Token![=>],
    code: TokenStream,
}

impl Parse for RepeatPrimesInput {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let n = input.parse()?;
        let _comma = input.parse()?;
        let placeholder = input.parse()?;
        let _arrow = input.parse()?;
        let code: proc_macro2::TokenStream = input.parse()?;
        Ok(RepeatPrimesInput {
            n,
            _comma,
            placeholder,
            _arrow,
            code: code.into(),
        })
    }
}

/// repeat_small_primes!(n, p => stuff) will repeat stuff once for each of the first n primes p.
#[proc_macro]
pub fn repeat_small_primes(input: TokenStream) -> TokenStream {
    let RepeatPrimesInput {
        n,
        placeholder,
        code,
        ..
    } = syn::parse_macro_input!(input as RepeatPrimesInput);
    let n: usize = n.base10_parse().unwrap();

    use malachite_base::num::factorization::traits::Primes;
    let primes = usize::primes().take(n).collect::<Vec<_>>();

    // Replace placeholder identifiers with prime literals
    fn replace_ident(
        stream: proc_macro2::TokenStream,
        placeholder: &Ident,
        lit: &proc_macro2::Literal,
    ) -> proc_macro2::TokenStream {
        use proc_macro2::{Group, TokenTree};
        let mut new_stream = proc_macro2::TokenStream::new();

        for tt in stream {
            match tt {
                TokenTree::Group(g) => {
                    let content = replace_ident(g.stream(), placeholder, lit);
                    let mut new_group = Group::new(g.delimiter(), content);
                    new_group.set_span(g.span());
                    new_stream.extend(std::iter::once(TokenTree::Group(new_group)));
                }
                TokenTree::Ident(id) if id == *placeholder => {
                    new_stream.extend(std::iter::once(TokenTree::Literal(lit.clone())));
                }
                _ => new_stream.extend(std::iter::once(tt)),
            }
        }

        new_stream
    }

    let expanded = primes.iter().map(|p| {
        let lit = proc_macro2::Literal::usize_unsuffixed(*p);
        let replaced = replace_ident(code.clone().into(), &placeholder, &lit);
        quote! { #replaced }
    });

    TokenStream::from(quote! { #(#expanded)* })
}
